### ISSUE TITLE
How the crawler works?

### ISSUE THREAD

**Issue by asac1995** [Ajinkgupta/khoj-Ai-Search-Engine#2]
Hello, how are websites indexed? Is there a predefined site list? Isn't there an option for visitors to add their sites to be indexed?

**Comment by Ajinkgupta** [comment]
For visitors, there is an option to submit their website via the spider: http://khoj.wexr.site/spider/ 

However, in the current demo version, I have added a simple protection to prevent others from entering their website.

you can find it from sourcecode in spider folder !!
As of now this project is not meant for production !

![image](https://github.com/Ajinkgupta/khoj/assets/76146259/773bc369-d2cb-4900-80ce-a9e0104e7802)

**Comment by asac1995** [comment]
Ah, okay. I tried to install the script but I didn't find the database, can you post it?
